
//1.................................................................******************************************......................................

//1.GLOBAL eXECUTION CONTEXT HOTA HA -->THIS KO REFER KARTA BROWSER ME YE->WINDOWS OBJECT KO OR NODE ME NULL OBJECT KO DEFINE KARTA HA
//2.TWO PHASE ME CODE RUN HOTA HA
//3.MEMORY CREATION PHRASE
//4.EXECUTION PHRASE
//5.EVERY FUNCTION IN THIS CREATE MCP AND EP

//1...................................................................****************************************......................................

//ISKE SATH ME EXECUTION CONTEXT 
//1.GLOBAL EXECUTION CONTEXT
//2.EVAL EXECUTION CONTEXT
//3.FUNCTION EXECUTION CONTEXT

//..................................................................******************************************.......................................

//CALL STACK WORKING WORKING AS LIFO

